### ISSUE TITLE
Deprecated warning

### ISSUE THREAD

**Issue by eltonplima** [twist-vector/elixir-matrix#6]
When I try to run any mix task like **mix docs** I the warnings bellow are raised.

warning: the char_list() type is deprecated, use charlist()
  lib/matrix.ex:502

warning: the char_list() type is deprecated, use charlist()
  lib/matrix.ex:502

**Comment by christhekeele** [comment]
Fixed in #3 by you, @eltonplima, if you wanna close this. :D
